import itertools
import logging
import os
from typing import Union, List

import numpy as np

from go import configuration
from go.west.launch import west_linear_multi
from go.utilities import get_prior_restart_file_day


class Model:
    """
    This is the main Model class that is used to run the GO model with a specified configuration.

    :param region: The region for the model.
    :type region: str

    :param problem: The problem for the model.
    :type problem: str

    :param complexity: The complexity for the model.
    :type complexity: str
    """
    # for HiGHS:  https://ergo-code.github.io/HiGHS/stable/options/definitions/#random_seed
    MAX_RANDOM_SEED_VALUE = 2147483647

    def __init__(
            self,
            region: str,
            problem: str,
            complexity: str,
            solver_name: str = "appsi_highs",
            solver_params: Union[None, dict] = None,
    ):
        """
        Initialize the Model with the specified region, problem, and complexity.

        :param region:              The region for the model. Either 'west', 'ercot', or 'east'
        :type region:               str

        :param problem:             The problem for the model. Either 'linear' or 'mip'
        :type problem:              str

        :param complexity:          The complexity for the model. Either 'simple' or 'multi'
        :type complexity:           str

        :param solver_name:         The solver to use.  Options are 'appsi_highs', 'gurobi', and 'cplex'
                                    Default: 'appsi_highs'
        :type solver_name:          str

        :param solver_params:       Parameter dictionary for the chosen solver to set options for the solver natively.
        :type solver_params:        Union[None, dict]; Default None

        """

        self.logger = logging.getLogger(__name__)

        if region == "west" and problem == "linear" and complexity == "multi":
            self.model = west_linear_multi
            self.logger.info(f"Using configuration:  {region}_{problem}_{complexity}")

        else:
            config_error_msg = f"Configuration: {region}_{problem}_{complexity} is not currently supported."
            self.logger.error(config_error_msg)
            raise AssertionError(config_error_msg)

        if solver_name not in ('appsi_highs', 'gurobi', 'cplex'):
            solver_error_msg = f"Solver '{solver_name}' not in available solvers:  'appsi_highs', 'gurobi', and 'cplex'"
            self.logger.error(solver_error_msg)
            raise AssertionError(solver_error_msg)

        else:
            self.solver_name = solver_name

        self.solver_params = solver_params

    def retry(        
        self, 
        config_file: Union[str, None] = None,
        n_days: int = 365,
        n_seeds: int = 1,
        solver_list: List[str] = ["simplex", "ipm", "pdlp"],
        dual_feasibility_tolerance_list: List[float] = [1e-07, 1e-06],
        primal_feasibility_tolerance_list: List[float] = [1e-07, 1e-06],
        ipm_optimality_tolerance_list: List[float] = [1e-08, 1e-07, 1e-06],
        simplex_strategy_list: List[int] = [0],
        simplex_scale_strategy_list: List[int] = [1],
        simplex_dual_edge_weight_strategy_list: List[int] = [-1],
        simplex_primal_edge_weight_strategy_list: List[int] = [-1],
        pdlp_e_restart_method: int = 2,
        pdlp_d_gap_tol_list: List[float] = [1e-4, 1e-3],
        retry_backoff: bool = True,
        restart_write_frequency: int = 10,
        **kwargs
    ):
        """
        Retry the model with different solver configurations and random seeds.

        The list of HiGHS options can be found here:  https://ergo-code.github.io/HiGHS/stable/options/definitions/
        The creation of this docstring, specifically the description of how HiGHS options are used, was generated with
        the assitance of OpenAI's GPT4-o model.  
        OpenAI. (2024). Response generated by ChatGPT on the topic of optimization solvers. Retrieved August 29, 2024, from https://chat.openai.com/.

        :param config_file:                                 Path to the configuration file. Default is None.
        :type config_file:                                  Union[str, None]

        :param n_days:                                      The number of the day in the calendar year to process through.
        :type n_days:                                       int; Default 365

        :param n_seeds:                                     Number of random seeds to try per solver. Default is 1.
        :type n_seeds:                                      int

        :param solver_list:                                 List of solvers to try. Options are any selection or combination of ["simplex", "ipm", "pdlp"].
                                                            simplex:
                                                                Description: The Simplex algorithm is a well-established method for solving linear programming (LP) 
                                                                problems. It works by moving along the edges of the feasible region of an LP problem to find the 
                                                                optimal solution at a vertex (or corner point).
                                                                Use Case: Simplex is widely used for problems where high precision is needed, especially in small 
                                                                to medium-sized LP problems where the feasible region is well-defined and the solution is expected 
                                                                to lie at a vertex. It is particularly effective when a feasible starting solution is known or can 
                                                                be easily obtained.
                                                            ipm:
                                                                Description: The Interior Point Method (IPM) is an algorithm used for solving large-scale linear and 
                                                                nonlinear convex optimization problems, including LPs, by traversing the interior of the feasible 
                                                                region rather than the boundaries. It uses a barrier function to avoid infeasibility and approaches 
                                                                the optimal solution from within the feasible region.
                                                                Use Case: IPM is particularly effective for very large-scale LPs and convex optimization problems 
                                                                where the Simplex method might be inefficient due to the sheer size of the problem. It is also preferred 
                                                                when the problem has a dense constraint matrix or when solving quadratic programming (QP) and other 
                                                                nonlinear problems.
                                                            pdlp:
                                                                Description: The PDLP (Primal-Dual Hybrid Gradient) is a relatively new and advanced method designed 
                                                                for solving large-scale linear optimization problems by using a primal-dual approach combined with 
                                                                gradient-based methods. It works by simultaneously updating both primal and dual variables to minimize 
                                                                the primal-dual gap, often using parallel computation for efficiency.
                                                                Use Case: PDLP is ideal for extremely large-scale LPs where traditional methods like Simplex or 
                                                                IPM might be too slow or resource-intensive. It is particularly suitable for problems where the 
                                                                primal and dual objectives can be efficiently approximated using gradient methods, making it effective 
                                                                in distributed or parallel computing environments.
                                                            Default is ["simplex", "ipm", "pdlp"]
        :type solver_list:                                  List[str]

        :param dual_feasibility_tolerance_list:             List of dual feasibility tolerances to try.
                                                            This dictates how closely the dual constraints must be satisfied for the solver to consider the solution 
                                                            feasible. It influences the trade-off between solution accuracy and computational effort. By adjusting this 
                                                            tolerance, users can control the precision of the dual solution, making it a key tool for tuning the performance 
                                                            of optimization solvers like the Simplex method and IPM.
                                                            A smaller dual feasibility tolerance is used to ensure that the dual constraints are closely satisfied. Larger 
                                                            values will provide less accuracy but faster computation time to solution.
                                                            Default is [1e-07, 1e-06]

        :type dual_feasibility_tolerance_list:              List[float]

        :param primal_feasibility_tolerance_list:           List of primal feasibility tolerances to try.
                                                            Controls the level of precision required for satisfying the primal constraints. By adjusting this tolerance, 
                                                            you can influence the trade-off between solution accuracy and computational effort. A smaller tolerance leads 
                                                            to more precise but potentially slower solutions, while a larger tolerance can speed up the process at the cost 
                                                            of some accuracy.
                                                            Default is [1e-07, 1e-06]
        :type primal_feasibility_tolerance_list:            List[float]

        :param ipm_optimality_tolerance_list:               List of IPM optimality tolerances to try.
                                                            Used in Interior Point Method (IPM) solvers to control the stopping criteria based on how close the current 
                                                            solution is to the optimal solution. Specifically, it determines when the solver should stop iterating 
                                                            because the solution is deemed “good enough” based on a combination of the primal and dual residuals and 
                                                            the duality gap.
                                                            Smaller values represent tighter tolerance which increases accuracy but requires much longer solve times.
                                                            Default is [1e-08, 1e-07, 1e-06]
        :type ipm_optimality_tolerance_list:                List[float]

        :param simplex_strategy_list:                       List of Simplex strategies to try. This is the method used by the Simplex solver to navigate through the 
                                                            feasible region of a linear programming (LP) problem in order to find the optimal solution.
                                                            Options: 0 => Choose; 1 => Dual (serial); 2 => Dual (PAMI); 3 => Dual (SIP); 4 => Primal
                                                            0: Model with choose which of the four methods it thinks is the best fit.
                                                            1: Dual Simplex Method:
                                                                Description: The dual simplex method maintains dual feasibility while allowing for temporary primal 
                                                                infeasibility. It iterates by improving the dual objective function while ensuring that the solution 
                                                                remains optimal with respect to the dual problem.
                                                                Use Case: Commonly used when starting from an infeasible solution or when working with problems where 
                                                                changes (like adding constraints) would otherwise disrupt primal feasibility.
                                                            2: Dual Simplex with Parallel Approximate Minimum Increase (PAMI):
                                                                Description: A variation of the dual simplex method that employs parallel processing to improve performance, 
                                                                particularly on large-scale problems. The PAMI strategy approximates the minimum increase needed to maintain 
                                                                feasibility in parallel, making it more efficient on modern multi-core processors.
                                                                Use Case: Suitable for large-scale linear programming problems where parallel computation can significantly 
                                                                reduce solve times.
                                                            3: Dual Simplex with Steepest Edge Price (SIP)
                                                                Description: This strategy is another variant of the dual simplex method, where the steepest edge pricing 
                                                                strategy is used to select the most promising direction for improvement. The idea is to choose the edge 
                                                                (or constraint) that will lead to the steepest descent in the objective function, aiming for faster convergence.
                                                                Use Case: Effective for problems where precision and stability in selecting the pivot element are crucial.
                                                            4: Primal Simplex Method:
	                                                            Description: The primal simplex method focuses on maintaining feasibility with respect to the primal 
                                                                constraints. It moves from one feasible solution to another by improving the objective function while 
                                                                ensuring that all constraints remain satisfied.
                                                                Use Case: Best suited for problems where a feasible initial solution is known or easily obtainable.
                                                            Default is [0].
        :type simplex_strategy_list:                        List[int]

        :param simplex_scale_strategy_list:                 List of simplex scale strategies to try. Options are a selection or combination of [0, 2, 3, 4, 5].
                                                            This is the method used by the Simplex solver to scale the problem’s data (objective function coefficients, 
                                                            constraint matrix, and right-hand side values) to improve numerical stability and performance during 
                                                            optimization. Scaling is particularly important in linear programming because it helps mitigate issues 
                                                            related to numerical precision, especially when the problem data vary widely in magnitude.
                                                            0: Off (No Scaling)
	                                                            Description: No scaling is applied to the problem data. The Simplex algorithm uses the original coefficients as they are.
                                                                Use Case: Best for problems where all coefficients are already in a similar range, or when the user has ensured that no 
                                                                large numerical differences exist in the data.
                                                            1: Choose
                                                                The model will choose what it believes is the most appropriate option.
	                                                        2: Equilibration
	                                                            Description: This method scales the rows and columns of the constraint matrix so that the largest element in each row and 
                                                                column is normalized, typically to 1. This strategy is common because it balances the constraint matrix, making the 
                                                                problem easier to solve.
	                                                            Use Case: Effective for problems where coefficients in the constraint matrix vary widely. It’s a general-purpose scaling 
                                                                method that works well in most cases.
	                                                        3: Forced Equilibration
	                                                            Description: Similar to equilibration but applied more aggressively. This strategy ensures even tighter scaling by forcing 
                                                                all rows and columns to have similar norms.
	                                                            Use Case: Used when standard equilibration does not sufficiently balance the problem, or when numerical stability is particularly crucial.
	                                                        4 and 5: Maximum Value Scaling (Variants 0 and 1)
	                                                            Description: These strategies scale the problem by the maximum absolute value found in the rows or columns. Different 
                                                                variants (e.g., max value 0 or 1) determine how aggressively the scaling is applied.
	                                                            Use Case: Useful in problems where some coefficients are orders of magnitude larger than others, ensuring that no single 
                                                                coefficient dominates the solution process.
                                                            Default is [1].
        :type simplex_scale_strategy_list:                  List[int]

        :param simplex_dual_edge_weight_strategy_list:      List of simplex dual edge weight strategies to try. Options are a selection or combination of [0, 1, 2].
                                                            This determines how the Simplex algorithm selects the entering variable during the dual Simplex method. 
                                                            This choice influences the efficiency and stability of the solver. 
                                                            -1: Model will choose which method may be most appropriate.
                                                            0: Dantzig’s Rule (Standard Dual Simplex)
	                                                            Description: This is the classic approach where the entering variable is chosen based on the largest 
                                                                coefficient in the reduced cost (objective row) vector. It tends to prioritize the variable that can 
                                                                improve the objective function the most in one step.
	                                                            Use Case: Simple and computationally efficient, making it a good general-purpose strategy, especially 
                                                                for smaller or well-behaved problems.
	                                                        1: Devex (Improved Dual Simplex)
	                                                            Description: An approximation of the steepest edge strategy, Devex uses a simplified calculation 
                                                                to approximate the best edge to follow, balancing efficiency and accuracy. It aims to avoid the 
                                                                numerical issues sometimes encountered with Dantzig’s Rule by spreading out the iterations more 
                                                                evenly across variables.
	                                                            Use Case: Often used in practice for large or numerically challenging problems where Dantzig’s Rule 
                                                                might cause instability or slow convergence.
	                                                        2: Steepest Edge
	                                                            Description: The steepest edge strategy selects the entering variable that results in the steepest 
                                                                descent in the objective function per unit change in the variable. This method is more 
                                                                computationally intensive but can lead to faster convergence by choosing the most promising direction.
	                                                            Use Case: Best for problems where convergence speed is critical and where the problem might have a 
                                                                complex or poorly conditioned feasible region.
                                                            Default [-1]
        :type simplex_dual_edge_weight_strategy_list:       List[int]

        :param simplex_primal_edge_weight_strategy_list:    List of simplex primal edge weight strategies to try. Options are a selection or combination of [0, 1, 2].
                                                            This setting is a critical parameter in the dual Simplex method that determines how the solver selects 
                                                            the entering variable. The choice of strategy can significantly impact the solver’s performance, 
                                                            with different strategies offering trade-offs between computational efficiency and numerical stability.
                                                            -1: Model will choose which method may be most appropriate.
                                                            0: Dantzig’s Rule (Standard Dual Simplex)
	                                                            Description: This strategy selects the entering variable based on the largest absolute value in the 
                                                                reduced cost vector, aiming to achieve the maximum immediate improvement in the objective function.
	                                                            Advantages: Simple and computationally efficient.
	                                                            Use Case: Suitable for problems where quick, heuristic-based decisions work well, particularly in 
                                                                smaller or well-conditioned problems.
	                                                        1: Devex (Approximate Steepest Edge)
	                                                            Description: An approximation of the steepest edge strategy, Devex selects the entering variable by 
                                                                approximating the most promising direction in terms of reducing the objective function, balancing 
                                                                computational effort and accuracy.
	                                                            Advantages: Offers a good compromise between computational cost and improved convergence behavior.
	                                                            Use Case: Commonly used in practice for large or numerically challenging problems where Dantzig’s Rule 
                                                                might lead to slow or unstable convergence.
	                                                        2: Steepest Edge
	                                                            Description: This strategy selects the entering variable by calculating the steepest descent direction, 
                                                                considering the ratio of the reduced cost to the norm of the pivot column. This is more computationally 
                                                                intensive but often results in faster convergence.
	                                                            Advantages: Can lead to significantly fewer iterations by making more informed decisions at each step.
	                                                            Use Case: Best for complex or poorly conditioned problems where faster convergence is necessary and the 
                                                                extra computational cost is justified.
                                                            Default is [-1]
        :type simplex_primal_edge_weight_strategy_list:     List[int]

        :param pdlp_e_restart_method:                       A parameter in the PDLP solver that controls the restart strategy during the optimization process. Restarting 
                                                            can help avoid stagnation and improve convergence by periodically resetting certain aspects of the solver.
                                                            0: No Restart
	                                                            Description: The solver does not use any restart strategy. It continues iterating without resetting any 
                                                                variables or states.
	                                                            Use Case: This method might be suitable when the problem is well-behaved and converges smoothly without 
                                                                any signs of stagnation or cycling.
	                                                        1: GPU-based Restart
	                                                            Description: This method utilizes GPU acceleration to perform the restart, potentially allowing for more frequent 
                                                                or efficient restarts by leveraging the parallel processing capabilities of modern GPUs.
	                                                            Use Case: Ideal for large-scale problems where GPU resources are available, and the solver can benefit from 
                                                                frequent restarts to improve convergence speed and reliability.
	                                                        2: CPU-based Restart
	                                                            Description: This method performs the restart using CPU resources. It may involve a more traditional or sequential 
                                                                approach compared to the GPU-based method.
	                                                            Use Case: Suitable for environments where GPU resources are not available, or the problem size or complexity 
                                                                does not justify GPU acceleration.
                                                            Default is 2.
        :type pdlp_e_restart_method:                        int

        :param pdlp_d_gap_tol_list:                         List of PDLP d-gap tolerances to try. 
                                                            Sets the duality gap tolerance in the PDLP solver, determining when the solver should stop based on the 
                                                            closeness of the primal and dual objective values. It plays a crucial role in balancing the precision of 
                                                            the solution with the computational effort required. A smaller tolerance results in a more accurate but 
                                                            potentially slower solution, while a larger tolerance allows for faster convergence at the cost of some precision.
                                                            Default is [1e-4, 1e-3]
        :type pdlp_d_gap_tol_list:                          List[float]

        :param retry_backoff:                               If True, after a retry sequence fails, backup to a previous restart file and try again
        :type retry_backoff:                                bool

        :param restart_write_frequency:                     Write a restart file after this many days.
        :type restart_write_frequency:                      int

        :param kwargs:                                      Additional keyword arguments.
        :type kwargs:                                       dict
        """

        self.logger.warning("[SOLVER RETRY MODE] Initiated")

        # compile a list of trials
        trial_list = []
        for solver in solver_list:

            # create random draw from possible seed values for the target number of seeds to try per solver
            seeds = [np.random.choice(Model.MAX_RANDOM_SEED_VALUE) for i in range(n_seeds)]

            # generate a trial per seed
            if solver == "simplex":

                # create all possible combinataions of simplex solve strategies
                combinations = list(itertools.product(
                    seeds,
                    simplex_strategy_list,
                    simplex_scale_strategy_list,
                    simplex_dual_edge_weight_strategy_list,
                    simplex_primal_edge_weight_strategy_list,
                    dual_feasibility_tolerance_list,
                    primal_feasibility_tolerance_list,
                    ipm_optimality_tolerance_list
                ))

                # add each strategy to the trail list
                for combo in combinations:
                    trial_list.append({
                        "solver": solver,
                        "random_seed": combo[0],
                        "simplex_strategy": combo[1],
                        "simplex_scale_strategy": combo[2],
                        "simplex_dual_edge_weight_strategy": combo[3],
                        "simplex_primal_edge_weight_strategy": combo[4],
                        "dual_feasibility_tolerance": combo[5],
                        "primal_feasibility_tolerance": combo[6],
                        "ipm_optimality_tolerance": combo[7]
                    })

            elif solver == "ipm":
                combinations = list(itertools.product(
                    seeds,
                    dual_feasibility_tolerance_list,
                    primal_feasibility_tolerance_list,
                    ipm_optimality_tolerance_list
                ))

                for combo in combinations:
                    trial_list.append({
                        "solver": solver,
                        "random_seed": combo[0],
                        "dual_feasibility_tolerance": combo[1],
                        "primal_feasibility_tolerance": combo[2],
                        "ipm_optimality_tolerance": combo[3],
                        # "time_limit": 3600,
                    })

            elif solver == "pdlp":
                combinations = list(itertools.product(
                    seeds,
                    dual_feasibility_tolerance_list,
                    primal_feasibility_tolerance_list,
                    ipm_optimality_tolerance_list,
                    pdlp_d_gap_tol_list,
                    [pdlp_e_restart_method]  # just box this in here to get the setting accounted for
                )) 

                for combo in combinations:
                    trial_list.append({
                        "solver": solver,
                        "random_seed": combo[0],
                        "dual_feasibility_tolerance": combo[1],
                        "primal_feasibility_tolerance": combo[2],
                        "ipm_optimality_tolerance": combo[3],
                        "pdlp_d_gap_tol": combo[4],
                        "pdlp_e_restart_method": combo[5]
                    })

            else:
                self.logger.warning(f'[SOLVER RETRY MODE] Solver selected "{solver}" is not a vaild option in ["simplex", "ipm", "pdlp"].  Skipping.')

        self.logger.info(f"[SOLVER RETRY MODE] Compiled a list of {len(trial_list)} strategies to try.")

        # run each trial until it either succeeds or fails
        success = False
        for modification in trial_list:

            # copy of the original parameters to modify so we do not inherit any previous modifications
            local_solver_parameters = self.solver_params.copy()

            # update solver paramters with trial parameters
            local_solver_parameters.update(modification)

            try:
                success_day = self.model(
                    config_file=config_file,
                    solver_name=self.solver_name,
                    solver_params=local_solver_parameters,
                    restart_day=None,
                    n_days=n_days,
                    break_run=True,
                    restart_write_frequency=restart_write_frequency,
                    **kwargs
                )

                success = True 
                break

            # if it fails, try the next one
            except Exception as e:
                solver_exception = e
                pass 

        if success:
            self.logger.info("[SOLVER RETRY MODE] Solution achieved.  Reverting back to original solver settings.")
            self.logger.info("[SOLVER RETRY MODE] Exiting solver retry mode.")

            if n_days > success_day:
                self.run(
                    config_file=config_file,
                    restart_day=None,
                    n_days=n_days,
                    retry_n_seeds=n_seeds,
                    retry_solver_list=solver_list,
                    retry_dual_feasibility_tolerance_list=dual_feasibility_tolerance_list,
                    retry_primal_feasibility_tolerance_list=primal_feasibility_tolerance_list,
                    retry_ipm_optimality_tolerance_list=ipm_optimality_tolerance_list,
                    retry_simplex_strategy_list=simplex_strategy_list,
                    retry_simplex_scale_strategy_list=simplex_scale_strategy_list,
                    retry_simplex_dual_edge_weight_strategy_list=simplex_dual_edge_weight_strategy_list,
                    retry_simplex_primal_edge_weight_strategy_list=simplex_primal_edge_weight_strategy_list,
                    retry_pdlp_e_restart_method=pdlp_e_restart_method,
                    retry_pdlp_d_gap_tol_list=pdlp_d_gap_tol_list,
                    restart_write_frequency=restart_write_frequency,
                    retry_backoff = False,
                    **kwargs
                )

            else:
                self.logger.info("All days completed successfully.")

        else:
            if retry_backoff:
                # backup to a previous restart file and start from there with a new seed
                config = configuration.generate_config(config_file=config_file, **kwargs)
                prior_restart_day = get_prior_restart_file_day(config.restart_file_directory)
                if prior_restart_day is None:
                    self.logger.error("[SOLVER RETRY MODE] Unable to find solution.  Exiting.")
                    raise solver_exception
                else:
                    # update seed
                    self.solver_params["random_seed"] = np.random.choice(Model.MAX_RANDOM_SEED_VALUE)
                    self.run(
                        config_file=config_file,
                        restart_day=prior_restart_day,
                        n_days=n_days,
                        retry_n_seeds=n_seeds,
                        retry_solver_list=solver_list,
                        retry_dual_feasibility_tolerance_list=dual_feasibility_tolerance_list,
                        retry_primal_feasibility_tolerance_list=primal_feasibility_tolerance_list,
                        retry_ipm_optimality_tolerance_list=ipm_optimality_tolerance_list,
                        retry_simplex_strategy_list=simplex_strategy_list,
                        retry_simplex_scale_strategy_list=simplex_scale_strategy_list,
                        retry_simplex_dual_edge_weight_strategy_list=simplex_dual_edge_weight_strategy_list,
                        retry_simplex_primal_edge_weight_strategy_list=simplex_primal_edge_weight_strategy_list,
                        retry_pdlp_e_restart_method=pdlp_e_restart_method,
                        retry_pdlp_d_gap_tol_list=pdlp_d_gap_tol_list,
                        restart_write_frequency=restart_write_frequency,
                        **kwargs
                    )
            else:
                self.logger.error("[SOLVER RETRY MODE] Unable to find solution.  Exiting.")
                raise solver_exception

    def run(
        self, 
        config_file: Union[str, None] = None, 
        restart_day: Union[None, int] = None,
        n_days: int = 365,
        allow_retry: bool = True,
        retry_n_seeds: int = 1,
        retry_solver_list: List[str] = ["simplex", "ipm", "pdlp"],
        retry_dual_feasibility_tolerance_list: List[float] = [1e-07, 1e-06],
        retry_primal_feasibility_tolerance_list: List[float] = [1e-07, 1e-06],
        retry_ipm_optimality_tolerance_list: List[float] = [1e-08, 1e-07, 1e-06],
        retry_simplex_strategy_list: List[int] = [0],
        retry_simplex_scale_strategy_list: List[int] = [1],
        retry_simplex_dual_edge_weight_strategy_list: List[int] = [-1],
        retry_simplex_primal_edge_weight_strategy_list: List[int] = [-1],
        retry_pdlp_e_restart_method: int = 2,
        retry_pdlp_d_gap_tol_list: List[float] = [1e-4, 1e-3],
        retry_backoff: bool = True,
        restart_write_frequency: int = 10,
        **kwargs
    ):
        """
        Run the GO model with a specified configuration.

        The list of HiGHS options can be found here:  https://ergo-code.github.io/HiGHS/stable/options/definitions/
        Retry options are only used if that mode is activated upon failure.
        The creation of this docstring, specifically the description of how HiGHS options are used, was generated with
        the assitance of OpenAI's GPT4-o model.  
        OpenAI. (2024). Response generated by ChatGPT on the topic of optimization solvers. Retrieved August 29, 2024, from https://chat.openai.com/.


        :param config_file:                                 The configuration file to use. If None, the default configuration is used.
        :type config_file:                                  Union[str, None]

        :param restart_day:                                 Day of the restart file to use. There must be a restart file for that day available.
                                                            If None, uses the largest day available among restart files or starts from day 1 if none exist. 
                                                            Default None
        :type restart_day:                                  Union[None, int]

        :param n_days:                                      The number of the day in the calendar year to process through.
                                                            Default 365       
        :type n_days:                                       int

        :param allow_retry:                                 If True, the model will try to retry a failed time step using what is specified in the 
                                                            retry parameters. After a solution is found, the model will revert back to the original 
                                                            solver parameter settings and continue on.
                                                            Default True.
        :type allow_retry:                                  bool

        :param retry_n_seeds:                               Number of random seeds to try per solver. Default is 1.
        :type retry_n_seeds:                                int

        :param retry_solver_list:                           List of solvers to try. Options are any selection or combination of ["simplex", "ipm", "pdlp"].
                                                            simplex:
                                                                Description: The Simplex algorithm is a well-established method for solving linear programming (LP) 
                                                                problems. It works by moving along the edges of the feasible region of an LP problem to find the 
                                                                optimal solution at a vertex (or corner point).
                                                                Use Case: Simplex is widely used for problems where high precision is needed, especially in small 
                                                                to medium-sized LP problems where the feasible region is well-defined and the solution is expected 
                                                                to lie at a vertex. It is particularly effective when a feasible starting solution is known or can 
                                                                be easily obtained.
                                                            ipm:
                                                                Description: The Interior Point Method (IPM) is an algorithm used for solving large-scale linear and 
                                                                nonlinear convex optimization problems, including LPs, by traversing the interior of the feasible 
                                                                region rather than the boundaries. It uses a barrier function to avoid infeasibility and approaches 
                                                                the optimal solution from within the feasible region.
                                                                Use Case: IPM is particularly effective for very large-scale LPs and convex optimization problems 
                                                                where the Simplex method might be inefficient due to the sheer size of the problem. It is also preferred 
                                                                when the problem has a dense constraint matrix or when solving quadratic programming (QP) and other 
                                                                nonlinear problems.
                                                            pdlp:
                                                                Description: The PDLP (Primal-Dual Hybrid Gradient) is a relatively new and advanced method designed 
                                                                for solving large-scale linear optimization problems by using a primal-dual approach combined with 
                                                                gradient-based methods. It works by simultaneously updating both primal and dual variables to minimize 
                                                                the primal-dual gap, often using parallel computation for efficiency.
                                                                Use Case: PDLP is ideal for extremely large-scale LPs where traditional methods like Simplex or 
                                                                IPM might be too slow or resource-intensive. It is particularly suitable for problems where the 
                                                                primal and dual objectives can be efficiently approximated using gradient methods, making it effective 
                                                                in distributed or parallel computing environments.
                                                            Default is ["simplex", "ipm", "pdlp"]
        :type retry_solver_list:                            List[str]

        :param retry_dual_feasibility_tolerance_list:       List of dual feasibility tolerances to try.
                                                            This dictates how closely the dual constraints must be satisfied for the solver to consider the solution 
                                                            feasible. It influences the trade-off between solution accuracy and computational effort. By adjusting this 
                                                            tolerance, users can control the precision of the dual solution, making it a key tool for tuning the performance 
                                                            of optimization solvers like the Simplex method and IPM.
                                                            A smaller dual feasibility tolerance is used to ensure that the dual constraints are closely satisfied. Larger 
                                                            values will provide less accuracy but faster computation time to solution.
                                                            Default is [1e-07, 1e-06]

        :type retry_dual_feasibility_tolerance_list:        List[float]

        :param retry_primal_feasibility_tolerance_list:     List of primal feasibility tolerances to try.
                                                            Controls the level of precision required for satisfying the primal constraints. By adjusting this tolerance, 
                                                            you can influence the trade-off between solution accuracy and computational effort. A smaller tolerance leads 
                                                            to more precise but potentially slower solutions, while a larger tolerance can speed up the process at the cost 
                                                            of some accuracy.
                                                            Default is [1e-07, 1e-06]
        :type retry_primal_feasibility_tolerance_list:      List[float]

        :param retry_ipm_optimality_tolerance_list:         List of IPM optimality tolerances to try.
                                                            Used in Interior Point Method (IPM) solvers to control the stopping criteria based on how close the current 
                                                            solution is to the optimal solution. Specifically, it determines when the solver should stop iterating 
                                                            because the solution is deemed “good enough” based on a combination of the primal and dual residuals and 
                                                            the duality gap.
                                                            Smaller values represent tighter tolerance which increases accuracy but requires much longer solve times.
                                                            Default is [1e-08, 1e-07, 1e-06]
        :type retry_ipm_optimality_tolerance_list:          List[float]

        :param retry_simplex_strategy_list:                 List of Simplex strategies to try. This is the method used by the Simplex solver to navigate through the 
                                                            feasible region of a linear programming (LP) problem in order to find the optimal solution.
                                                            Options: 0 => Choose; 1 => Dual (serial); 2 => Dual (PAMI); 3 => Dual (SIP); 4 => Primal
                                                            0: Model with choose which of the four methods it thinks is the best fit.
                                                            1: Dual Simplex Method:
                                                                Description: The dual simplex method maintains dual feasibility while allowing for temporary primal 
                                                                infeasibility. It iterates by improving the dual objective function while ensuring that the solution 
                                                                remains optimal with respect to the dual problem.
                                                                Use Case: Commonly used when starting from an infeasible solution or when working with problems where 
                                                                changes (like adding constraints) would otherwise disrupt primal feasibility.
                                                            2: Dual Simplex with Parallel Approximate Minimum Increase (PAMI):
                                                                Description: A variation of the dual simplex method that employs parallel processing to improve performance, 
                                                                particularly on large-scale problems. The PAMI strategy approximates the minimum increase needed to maintain 
                                                                feasibility in parallel, making it more efficient on modern multi-core processors.
                                                                Use Case: Suitable for large-scale linear programming problems where parallel computation can significantly 
                                                                reduce solve times.
                                                            3: Dual Simplex with Steepest Edge Price (SIP)
                                                                Description: This strategy is another variant of the dual simplex method, where the steepest edge pricing 
                                                                strategy is used to select the most promising direction for improvement. The idea is to choose the edge 
                                                                (or constraint) that will lead to the steepest descent in the objective function, aiming for faster convergence.
                                                                Use Case: Effective for problems where precision and stability in selecting the pivot element are crucial.
                                                            4: Primal Simplex Method:
	                                                            Description: The primal simplex method focuses on maintaining feasibility with respect to the primal 
                                                                constraints. It moves from one feasible solution to another by improving the objective function while 
                                                                ensuring that all constraints remain satisfied.
                                                                Use Case: Best suited for problems where a feasible initial solution is known or easily obtainable.
                                                            Default is [0].
        :type retry_simplex_strategy_list:                  List[int]

        :param retry_simplex_scale_strategy_list:           List of simplex scale strategies to try. Options are a selection or combination of [0, 2, 3, 4, 5].
                                                            This is the method used by the Simplex solver to scale the problem’s data (objective function coefficients, 
                                                            constraint matrix, and right-hand side values) to improve numerical stability and performance during 
                                                            optimization. Scaling is particularly important in linear programming because it helps mitigate issues 
                                                            related to numerical precision, especially when the problem data vary widely in magnitude.
                                                            0: Off (No Scaling)
	                                                            Description: No scaling is applied to the problem data. The Simplex algorithm uses the original coefficients as they are.
                                                                Use Case: Best for problems where all coefficients are already in a similar range, or when the user has ensured that no 
                                                                large numerical differences exist in the data.
                                                            1: Choose
                                                                The model will choose what it believes is the most appropriate option.
	                                                        2: Equilibration
	                                                            Description: This method scales the rows and columns of the constraint matrix so that the largest element in each row and 
                                                                column is normalized, typically to 1. This strategy is common because it balances the constraint matrix, making the 
                                                                problem easier to solve.
	                                                            Use Case: Effective for problems where coefficients in the constraint matrix vary widely. It’s a general-purpose scaling 
                                                                method that works well in most cases.
	                                                        3: Forced Equilibration
	                                                            Description: Similar to equilibration but applied more aggressively. This strategy ensures even tighter scaling by forcing 
                                                                all rows and columns to have similar norms.
	                                                            Use Case: Used when standard equilibration does not sufficiently balance the problem, or when numerical stability is particularly crucial.
	                                                        4 and 5: Maximum Value Scaling (Variants 0 and 1)
	                                                            Description: These strategies scale the problem by the maximum absolute value found in the rows or columns. Different 
                                                                variants (e.g., max value 0 or 1) determine how aggressively the scaling is applied.
	                                                            Use Case: Useful in problems where some coefficients are orders of magnitude larger than others, ensuring that no single 
                                                                coefficient dominates the solution process.
                                                            Default is [1].
        :type retry_simplex_scale_strategy_list:            List[int]

        :param retry_simplex_dual_edge_weight_strategy_list: List of simplex dual edge weight strategies to try. Options are a selection or combination of [0, 1, 2].
                                                            This determines how the Simplex algorithm selects the entering variable during the dual Simplex method. 
                                                            This choice influences the efficiency and stability of the solver. 
                                                            -1: Model will choose which method may be most appropriate.
                                                            0: Dantzig’s Rule (Standard Dual Simplex)
	                                                            Description: This is the classic approach where the entering variable is chosen based on the largest 
                                                                coefficient in the reduced cost (objective row) vector. It tends to prioritize the variable that can 
                                                                improve the objective function the most in one step.
	                                                            Use Case: Simple and computationally efficient, making it a good general-purpose strategy, especially 
                                                                for smaller or well-behaved problems.
	                                                        1: Devex (Improved Dual Simplex)
	                                                            Description: An approximation of the steepest edge strategy, Devex uses a simplified calculation 
                                                                to approximate the best edge to follow, balancing efficiency and accuracy. It aims to avoid the 
                                                                numerical issues sometimes encountered with Dantzig’s Rule by spreading out the iterations more 
                                                                evenly across variables.
	                                                            Use Case: Often used in practice for large or numerically challenging problems where Dantzig’s Rule 
                                                                might cause instability or slow convergence.
	                                                        2: Steepest Edge
	                                                            Description: The steepest edge strategy selects the entering variable that results in the steepest 
                                                                descent in the objective function per unit change in the variable. This method is more 
                                                                computationally intensive but can lead to faster convergence by choosing the most promising direction.
	                                                            Use Case: Best for problems where convergence speed is critical and where the problem might have a 
                                                                complex or poorly conditioned feasible region.
                                                            Default [-1]
        :type retry_simplex_dual_edge_weight_strategy_list: List[int]

        :param retry_simplex_primal_edge_weight_strategy_list: List of simplex primal edge weight strategies to try. Options are a selection or combination of [0, 1, 2].
                                                            This setting is a critical parameter in the dual Simplex method that determines how the solver selects 
                                                            the entering variable. The choice of strategy can significantly impact the solver’s performance, 
                                                            with different strategies offering trade-offs between computational efficiency and numerical stability.
                                                            -1: Model will choose which method may be most appropriate.
                                                            0: Dantzig’s Rule (Standard Dual Simplex)
	                                                            Description: This strategy selects the entering variable based on the largest absolute value in the 
                                                                reduced cost vector, aiming to achieve the maximum immediate improvement in the objective function.
	                                                            Advantages: Simple and computationally efficient.
	                                                            Use Case: Suitable for problems where quick, heuristic-based decisions work well, particularly in 
                                                                smaller or well-conditioned problems.
	                                                        1: Devex (Approximate Steepest Edge)
	                                                            Description: An approximation of the steepest edge strategy, Devex selects the entering variable by 
                                                                approximating the most promising direction in terms of reducing the objective function, balancing 
                                                                computational effort and accuracy.
	                                                            Advantages: Offers a good compromise between computational cost and improved convergence behavior.
	                                                            Use Case: Commonly used in practice for large or numerically challenging problems where Dantzig’s Rule 
                                                                might lead to slow or unstable convergence.
	                                                        2: Steepest Edge
	                                                            Description: This strategy selects the entering variable by calculating the steepest descent direction, 
                                                                considering the ratio of the reduced cost to the norm of the pivot column. This is more computationally 
                                                                intensive but often results in faster convergence.
	                                                            Advantages: Can lead to significantly fewer iterations by making more informed decisions at each step.
	                                                            Use Case: Best for complex or poorly conditioned problems where faster convergence is necessary and the 
                                                                extra computational cost is justified.
                                                            Default is [-1]
        :type retry_simplex_primal_edge_weight_strategy_list: List[int]

        :param retry_pdlp_e_restart_method:                 A parameter in the PDLP solver that controls the restart strategy during the optimization process. Restarting 
                                                            can help avoid stagnation and improve convergence by periodically resetting certain aspects of the solver.
                                                            0: No Restart
	                                                            Description: The solver does not use any restart strategy. It continues iterating without resetting any 
                                                                variables or states.
	                                                            Use Case: This method might be suitable when the problem is well-behaved and converges smoothly without 
                                                                any signs of stagnation or cycling.
	                                                        1: GPU-based Restart
	                                                            Description: This method utilizes GPU acceleration to perform the restart, potentially allowing for more frequent 
                                                                or efficient restarts by leveraging the parallel processing capabilities of modern GPUs.
	                                                            Use Case: Ideal for large-scale problems where GPU resources are available, and the solver can benefit from 
                                                                frequent restarts to improve convergence speed and reliability.
	                                                        2: CPU-based Restart
	                                                            Description: This method performs the restart using CPU resources. It may involve a more traditional or sequential 
                                                                approach compared to the GPU-based method.
	                                                            Use Case: Suitable for environments where GPU resources are not available, or the problem size or complexity 
                                                                does not justify GPU acceleration.
                                                            Default is 2.
        :type retry_pdlp_e_restart_method:                  int

        :param retry_pdlp_d_gap_tol_list:                   List of PDLP d-gap tolerances to try. 
                                                            Sets the duality gap tolerance in the PDLP solver, determining when the solver should stop based on the 
                                                            closeness of the primal and dual objective values. It plays a crucial role in balancing the precision of 
                                                            the solution with the computational effort required. A smaller tolerance results in a more accurate but 
                                                            potentially slower solution, while a larger tolerance allows for faster convergence at the cost of some precision.
                                                            Default is [1e-4, 1e-3]
        :type retry_pdlp_d_gap_tol_list:                    List[float]

        :param retry_backoff:                               If True, after a retry sequence fails, backup to a previous restart file and try again
        :type retry_backoff:                                bool

        :param restart_write_frequency:                     Write a restart file after this many days.
        :type restart_write_frequency:                      int

        :param kwargs:                                      Additional keyword arguments to pass to the model.
        :type kwargs:                                       dict
        """

        try:

            success_day = self.model(
                config_file=config_file,
                solver_name=self.solver_name,
                solver_params=self.solver_params,
                n_days=n_days,
                restart_day=restart_day,
                restart_write_frequency=restart_write_frequency,
                **kwargs
            )

            self.logger.info("All days completed successfully.")

        except Exception as e:

            if allow_retry:
                self.retry(
                    config_file=config_file,
                    n_days=n_days,
                    n_seeds=retry_n_seeds,
                    solver_list=retry_solver_list,
                    dual_feasibility_tolerance_list=retry_dual_feasibility_tolerance_list,
                    primal_feasibility_tolerance_list=retry_primal_feasibility_tolerance_list,
                    ipm_optimality_tolerance_list=retry_ipm_optimality_tolerance_list,
                    simplex_strategy_list=retry_simplex_strategy_list,
                    simplex_scale_strategy_list=retry_simplex_scale_strategy_list,
                    simplex_dual_edge_weight_strategy_list=retry_simplex_dual_edge_weight_strategy_list,
                    simplex_primal_edge_weight_strategy_list=retry_simplex_primal_edge_weight_strategy_list,
                    pdlp_e_restart_method=retry_pdlp_e_restart_method,
                    pdlp_d_gap_tol_list=retry_pdlp_d_gap_tol_list,
                    retry_backoff=retry_backoff,
                    restart_write_frequency=restart_write_frequency,
                )

            else:
                raise e
