# main files are the following
#  WECC_LP.py:    solving the unit commitment and economic dispatch problem using linear programming
#  WECC_MILP.py:  solving the unit commitment and economic dispatch problem using mixed integer linear programming


from pypyo.environ import *

model = AbstractModel()

######=================================================########
######               Segment B.1                       ########
######=================================================########

### Generators by fuel-type
self.model.Coal = Set()
self.model.Oil = Set()
self.model.Gas = Set()
self.model.Hydro = Set()
self.model.Solar = Set()
self.model.Wind = Set()

#all generators
self.model.Thermal = self.model.Coal | self.model.Oil | self.model.Gas
self.model.Dispatchable = self.model.Thermal | self.model.Hydro 
self.model.Generators = self.model.Dispatchable | self.model.Solar | self.model.Wind


# transmission sets
self.model.lines = Set() 
self.model.buses = Set()

#Generator type
self.model.typ = Param(self.model.Generators,within=Any)

#Node name
self.model.node = Param(self.model.Generators,within=Any)

#Max capacity
self.model.maxcap = Param(self.model.Generators)

#Min capacity
self.model.mincap = Param(self.model.Generators)

#Heat rate
self.model.heat_rate = Param(self.model.Generators)

#Variable O&M
self.model.var_om = Param(self.model.Generators)

#Fixed O&M cost
self.model.no_load  = Param(self.model.Generators)

#Start cost
self.model.st_cost = Param(self.model.Generators)

#Ramp rate
self.model.ramp  = Param(self.model.Generators)

#Minimun up time
self.model.minup = Param(self.model.Generators)

#Minimun down time
self.model.mindn = Param(self.model.Generators)


self.model.Reactance = Param(self.model.lines)
self.model.FlowLim = Param(self.model.lines)
self.model.LinetoBusMap=Param(self.model.lines,self.model.buses)
self.model.BustoUnitMap=Param(self.model.Generators,self.model.buses)

# ### Transmission Loss as a %discount on production
# self.model.TransLoss = Param(within=NonNegativeReals)

# ### Maximum line-usage as a percent of line-capacity
# self.model.n1criterion = Param(within=NonNegativeReals)

# ### Minimum spinning reserve as a percent of total reserve
# self.model.spin_margin = Param(within=NonNegativeReals)


######=================================================########
######               Segment B.5                       ########
######=================================================########

######===== Parameters/initial_conditions to run simulation ======####### 
## Full range of time series information
self.model.SimHours = Param(within=PositiveIntegers)
self.model.SH_periods = RangeSet(1,self.model.SimHours+1)
self.model.SimDays = Param(within=PositiveIntegers)
self.model.SD_periods = RangeSet(1,self.model.SimDays+1)

# Operating horizon information 
self.model.HorizonHours = Param(within=PositiveIntegers)
self.model.HH_periods = RangeSet(0,self.model.HorizonHours)
self.model.hh_periods = RangeSet(1,self.model.HorizonHours)
self.model.ramp_periods = RangeSet(2,24)

######=================================================########
######               Segment B.6                       ########
######=================================================########

#Demand over simulation period
self.model.SimDemand = Param(self.model.buses*self.model.SH_periods, within=NonNegativeReals)

#Horizon demand
self.model.HorizonDemand = Param(self.model.buses*self.model.hh_periods,within=NonNegativeReals,mutable=True)

#Reserve for the entire system
# self.model.SimReserves = Param(self.model.SH_periods, within=NonNegativeReals)
# self.model.HorizonReserves = Param(self.model.hh_periods, within=NonNegativeReals,mutable=True)

##Variable resources over simulation period
self.model.SimHydro = Param(self.model.Hydro, self.model.SH_periods, within=NonNegativeReals)
self.model.SimSolar = Param(self.model.Solar, self.model.SH_periods, within=NonNegativeReals)
self.model.SimWind = Param(self.model.Wind, self.model.SH_periods, within=NonNegativeReals)

#Variable resources over horizon
self.model.HorizonHydro = Param(self.model.Hydro,within=NonNegativeReals,mutable=True)
self.model.HorizonSolar = Param(self.model.Solar,self.model.hh_periods,within=NonNegativeReals,mutable=True)
self.model.HorizonWind = Param(self.model.Wind,self.model.hh_periods,within=NonNegativeReals,mutable=True)

#Must run resources
self.model.Must = Param(self.model.buses,within=NonNegativeReals)

######=================================================########
######               Segment B.7                       ########
######=================================================########

######=======================Decision variables======================########
##Amount of day-ahead energy generated by each generator at each hour
self.model.mwh = Var(self.model.Generators,self.model.HH_periods, within=NonNegativeReals,initialize=0)

#1 if unit is on in hour i, otherwise 0
self.model.on = Var(self.model.Dispatchable,self.model.HH_periods, within=Binary, initialize=0)

#1 if unit is switching on in hour i, otherwise 0
self.model.switch = Var(self.model.Dispatchable,self.model.HH_periods, within=Binary,initialize=0)

# #Amount of spining reserve offered by an unit in each hour
# self.model.srsv = Var(self.model.Generators,self.model.HH_periods, within=NonNegativeReals,initialize=0)

# #Amount of non-sping reserve offered by an unit in each hour
# self.model.nrsv = Var(self.model.Generators,self.model.HH_periods, within=NonNegativeReals,initialize=0)

# slack variables
self.model.S = Var(self.model.buses,self.model.hh_periods, within=NonNegativeReals,initialize=0)


# transmission line variables 
self.model.Flow= Var(self.model.lines,self.model.hh_periods)
self.model.Theta= Var(self.model.buses,self.model.hh_periods)


######=================================================########
######               Segment B.8                       ########
######=================================================########

######================Objective function=============########

def SysCost(model):
    fixed = sum(self.model.no_load[j]*self.model.on[j,i] for i in self.model.hh_periods for j in self.model.Dispatchable)
    starts = sum(self.model.st_cost[j]*self.model.switch[j,i] for i in self.model.hh_periods for j in self.model.Dispatchable)
    coal = sum(self.model.mwh[j,i]*(self.model.heat_rate[j]*2 + self.model.var_om[j]) for i in self.model.hh_periods for j in self.model.Coal)  
    oil = sum(self.model.mwh[j,i]*(self.model.heat_rate[j]*10 + self.model.var_om[j]) for i in self.model.hh_periods for j in self.model.Oil)
    gas = sum(self.model.mwh[j,i]*(self.model.heat_rate[j]*4.5 + self.model.var_om[j]) for i in self.model.hh_periods for j in self.model.Gas)
    slack = sum(self.model.S[z,i]*100000 for i in self.model.hh_periods for z in self.model.buses)
    
    return coal + oil + gas + slack + fixed + starts 

self.model.SystemCost = Objective(rule=SysCost, sense=minimize)



######=================================================########
######               Segment B.9                      ########
######=================================================########

#####========== Logical Constraint =========#############
# Switch is 1 if unit is turned on in current period
def SwitchCon(model,j,i):
    return self.model.switch[j,i] >= 1 - self.model.on[j,i-1] - (1 - self.model.on[j,i])
self.model.SwitchConstraint = Constraint(self.model.Dispatchable,self.model.hh_periods,rule = SwitchCon)


######========== Up/Down Time Constraint =========#############
#Min Up time
def MinUp(model,j,i,k):
    if i > 0 and k > i and k < min(i+self.model.minup[j]-1,self.model.HorizonHours):
        return self.model.on[j,i] - self.model.on[j,i-1] <= self.model.on[j,k]
    else: 
        return Constraint.Skip
self.model.MinimumUp = Constraint(self.model.Thermal,self.model.HH_periods,self.model.HH_periods,rule=MinUp)

##Min Down time
def MinDown(model,j,i,k):
    if i > 0 and k > i and k < min(i+self.model.mindn[j]-1,self.model.HorizonHours):
        return self.model.on[j,i-1] - self.model.on[j,i] <= 1 - self.model.on[j,k]
    else:
        return Constraint.Skip
self.model.MinimumDown = Constraint(self.model.Thermal,self.model.HH_periods,self.model.HH_periods,rule=MinDown)


#####==========Ramp Rate Constraints =========#############
def Ramp1(model,j,i):
    a = self.model.mwh[j,i]
    b = self.model.mwh[j,i-1]
    return a - b <= self.model.ramp[j] 
self.model.RampCon1 = Constraint(self.model.Thermal,self.model.ramp_periods,rule=Ramp1)

def Ramp2(model,j,i):
    a = self.model.mwh[j,i]
    b = self.model.mwh[j,i-1]
    return b - a <= self.model.ramp[j] 
self.model.RampCon2 = Constraint(self.model.Thermal,self.model.ramp_periods,rule=Ramp2)


######=================================================########
######               Segment B.10                      ########
######=================================================########

#####=========== Capacity Constraints ============##########
# Constraints for Max & Min Capacity of dispatchable resources
def MaxC(model,j,i):
    return self.model.mwh[j,i]  <= self.model.on[j,i] * self.model.maxcap[j] 
self.model.MaxCap= Constraint(self.model.Dispatchable,self.model.hh_periods,rule=MaxC)


def MinC(model,j,i):
    return self.model.mwh[j,i] >= self.model.on[j,i] * self.model.mincap[j]
self.model.MinCap= Constraint(self.model.Dispatchable,self.model.hh_periods,rule=MinC)


#Max capacity constraints on domestic hydropower 
def HydroC(model,j,i):
    daily = sum(self.model.mwh[j,i] for i in self.model.hh_periods)
    return  daily <= self.model.HorizonHydro[j]    
self.model.HydroConstraint= Constraint(self.model.Hydro,self.model.hh_periods,rule=HydroC)


#Max capacity constraints on solar
def SolarC(model,j,i): 
    return  self.model.mwh[j,i] <= self.model.HorizonSolar[j,i]    
self.model.SolarConstraint= Constraint(self.model.Solar,self.model.hh_periods,rule=SolarC)

#Max capacity constraints on wind
def WindC(model,j,i): 
    return  self.model.mwh[j,i] <= self.model.HorizonWind[j,i]    
self.model.WindConstraint= Constraint(self.model.Wind,self.model.hh_periods,rule=WindC)


######=================================================########
######               Segment B.11.1                    ########
######=================================================########

def Nodal_Balance(model,z,i):
    power_flow = sum(self.model.Flow[l,i]*self.model.LinetoBusMap[l,z] for l in self.model.lines)   
    gen = sum(self.model.mwh[j,i]*self.model.BustoUnitMap[j,z] for j in self.model.Generators)    
    slack = self.model.S[z,i]
    must_run = self.model.Must[z]
    return gen + slack + must_run - power_flow == self.model.HorizonDemand[z,i] 
self.model.Node_Constraint = Constraint(self.model.buses,self.model.hh_periods,rule=Nodal_Balance)

def Flow_line(model,l,i):
    value = sum(self.model.Theta[z,i]*self.model.LinetoBusMap[l,z] for z in self.model.buses)
    return  100*value == self.model.Flow[l,i]*self.model.Reactance[l]
self.model.FlowL_Constraint = Constraint(self.model.lines,self.model.hh_periods,rule=Flow_line)

def Theta_bus(model,i):
        return self.model.Theta['MESA_CAL_20',i] == 0
self.model.ThetaB_Constraint = Constraint(self.model.hh_periods,rule=Theta_bus)

def FlowUP_line(model,l,i):
    return  self.model.Flow[l,i] <= self.model.FlowLim[l]
self.model.FlowU_Constraint = Constraint(self.model.lines,self.model.hh_periods,rule=FlowUP_line)

def FlowLow_line(model,l,i):
    return  -1*self.model.Flow[l,i] <= self.model.FlowLim[l]
self.model.FlowLL_Constraint = Constraint(self.model.lines,self.model.hh_periods,rule=FlowLow_line)

######=================================================########
######               Segment B.13                      ########
######=================================================########

######===================Reserve and zero-sum constraints ==================########

# ##System Reserve Requirement
# def SysReserve(model,i):
#     return sum(self.model.srsv[j,i] for j in self.model.ResGenerators) + sum(self.model.nrsv[j,i] for j in self.model.ResGenerators) >= self.model.HorizonReserves[i]
# self.model.SystemReserve = Constraint(self.model.hh_periods,rule=SysReserve)

# ##Spinning Reserve Requirement
# def SpinningReq(model,i):
#     return sum(self.model.srsv[j,i] for j in self.model.ResGenerators) >= self.model.spin_margin * self.model.HorizonReserves[i] 
# self.model.SpinReq = Constraint(self.model.hh_periods,rule=SpinningReq)           

# ##Spinning reserve can only be offered by units that are online
# def SpinningReq2(model,j,i):
#     return self.model.srsv[j,i] <= self.model.on[j,i]*self.model.maxcap[j]
# self.model.SpinReq2= Constraint(self.model.Generators,self.model.hh_periods,rule=SpinningReq2) 

# ##Non-Spinning reserve can only be offered by units that are offline
# def NonSpinningReq(model,j,i):
#     return self.model.nrsv[j,i] <= (1 - self.model.on[j,i])*self.model.maxcap[j]
# self.model.NonSpinReq= Constraint(self.model.Generators,self.model.hh_periods,rule=NonSpinningReq)


# ######========== Zero Sum Constraint =========#############
# def ZeroSum(model,j,i):
#     return self.model.mwh[j,i] + self.model.srsv[j,i] + self.model.nrsv[j,i] <= self.model.maxcap[j]
# self.model.ZeroSumConstraint=Constraint(self.model.Generators,self.model.hh_periods,rule=ZeroSum)


######======================================#############
######==========        End        =========#############
######=======================================############

